### PR TITLE
[E2E] Adding animal only e2e testing scenario

### LINKED ISSUE #3053: [E2E Testing] Add `animal_only` and `field_only` e2e testing
Following the outline of what we've been doing to date, add expected e2e results for the 2 new simulation types - `animals_only` and `field_only` and incorporate them into the e2e testing process.

Not 100% sure this is necessary given these are isolated versions of the other simulation types but wanted to make an issue for it to at least discuss further at a grooming session.

### PR DESCRIPTION
**Pull request by matthew7838**
python main.py -p input/metadata/update_end_to_end_testing_tm_metadata.json -c
### Context

Issue(s) closed by this pull request: closes #3053

### What

- Fix: `EmissionsEstimator.__init__` crashed (`'NoneType' object has no attribute 'values'`) whenever feed-storage inputs are excluded from the pool, which is always true for `animals_only`/`field_only`. Now reads them with `required=False` and defaults to `{}`.
- New `animals_only_e2e` end-to-end test (Animal domain), same structure as the existing freestall/open_lot/field_and_feed variants, plus a new prefix schema block in `default.json`.
- Regenerated expected results for all four e2e variants.
- Unit test for the fixed `EmissionsEstimator` path.

### Why

`animals_only`/`field_only` have been broken since #3002 — their inputs exclude feed storage, but `EmissionsEstimator` always reads it.

### How

Guard the two feed-storage reads the same way `SimulationEngine` already guards its own (`if self.simulate_feed`). No behavior change for simulation types that have feed storage.

### Test plan

- New test: `test_emissions_estimator_init_without_feed_storage_data`.
- Run full e2e testing.

### Input Changes

Added `animals_only` e2e config/metadata/filters. Added `animals_only_e2e` entries to the e2e task and result-path files, and its schema block in `default.json`. Regenerated expected results for freestall/open_lot/field_and_feed.

### Output Changes

- N/A

#### Filter

```json

```

### CODE REVIEW

File: RUFAS/EEE/emissions.py [hunk 1]
```diff
@@ -116,8 +116,8 @@ def __init__(self) -> None:
         self._missing_purchased_ids: set[str] = set()
         self._missing_land_use_ids: set[str] = set()
 
-        feed_storage_configs = self.im.get_data("feed_storage_configurations")
-        feed_storage_instances = self.im.get_data("feed_storage_instances")
+        feed_storage_configs = self.im.get_data("feed_storage_configurations", required=False) or {}
+        feed_storage_instances = self.im.get_data("feed_storage_instances", required=False) or {}
```
Comment (ew3361zh) [inline RUFAS/EEE/emissions.py]: In #3132 I'm passing in the `SimulationEngine` value for `simulate_feed` to determine whether or not to run these checks. I think I prefer that approach and might say to wait until that is merged in rather than adding this different approach here but am open to conversation if you feel strongly the other way.

https://github.com/RuminantFarmSystems/RuFaS/pull/3132/changes#diff-dcc9057518396e5889473a7db75d85cd2f4ccc82d144680459008933211caa06R147

**Review by ew3361zh — APPROVED** [review]
LGTM, a couple small things:

1. I got a fail on `Animals` for `open_lot`:

```
{
  "DISCLAIMER": "Under construction, use the results with caution.",
  "Animal.iterable_item_removed": {
    "values": [
      {
        "root['AnimalModuleReporter.report_herd_statistics_data.herd_milk_fat_kg']['values'][169]": 1148.1694999026709
      }
    ]
  },
  "Animal.end_to_end_testing_passing": {
    "values": [
      false
    ]
  }
}
```

2. See note about the emissions.py fix you applied and what I'm doing in PR #3132.

File: RUFAS/EEE/emissions.py (hunk 1 above)
Comment (matthew7838) [reply RUFAS/EEE/emissions.py]: I agree, I'll wait until the merge of #3132

Comment (matthew7838) [reply RUFAS/EEE/emissions.py]: I agree, I'll wait for it to merge.

**Comment by matthew7838** [comment]
> 1. I got a fail on `Animals` for `open_lot`:

Same pattern on dev, will update them once this PR is ready to merge.

**Review by allisterakun — APPROVED** [review]
Generally looks good, but `Animal` failed on `freestall` and `animals_only`:

> Summary of e2e results:

freestall_e2e results:
  Animal: Failing
  CropAndSoil: Passing
  Manure: Passing
  Feed: Passing

open_lot_e2e results:
  Animal: Passing
  CropAndSoil: Passing
  Manure: Passing
  Feed: Passing

field_and_feed_e2e results:
  Animal: n/a
  CropAndSoil: Passing
  Manure: Passing
  Feed: Passing

animals_only_e2e results:
  Animal: Failing
  CropAndSoil: n/a
  Manure: n/a


Both of them seems to be changes in `vwp_cow_num`:
```json
{
  "DISCLAIMER": "Under construction, use the results with caution.",
  "Animal.values_changed": {
    "values": [
      {
        "root['AnimalModuleReporter.report_herd_statistics_data.vwp_cow_num']['values'][0]": {
          "new_value": 0,
          "old_value": 31
        }
      }
    ]
  },
  "Animal.iterable_item_removed": {
    "values": [
      {
        "root['AnimalModuleReporter.report_herd_statistics_data.vwp_cow_num']['values'][1]": 30,
        "root['AnimalModuleReporter.report_herd_statistics_data.vwp_cow_num']['values'][6]": 27,
        "root['AnimalModuleReporter.report_herd_statistics_data.vwp_cow_num']['values'][9]": 28,
        "root['AnimalModuleReporter.report_herd_statistics_data.vwp_cow_num']['values'][13]": 29,
        "root['AnimalModuleReporter.report_herd_statistics_data.vwp_cow_num']['values'][23]": 32,
        "root['AnimalModuleReporter.report_herd_statistics_data.vwp_cow_num']['values'][26]": 33,
        "root['AnimalModuleReporter.report_herd_statistics_data.vwp_cow_num']['values'][58]": 26,
        "root['AnimalModuleReporter.report_herd_statistics_data.vwp_cow_num']['values'][62]": 23,
        "root['AnimalModuleReporter.report_herd_statistics_data.vwp_cow_num']['values'][65]": 22,
        "root['AnimalModuleReporter.report_herd_statistics_data.vwp_cow_num']['values'][74]": 24,
        "root['AnimalModuleReporter.report_herd_statistics_data.vwp_cow_num']['values'][111]": 25,
        "root['AnimalModuleReporter.report_herd_statistics_data.vwp_cow_num']['values'][130]": 21,
        "root['AnimalModuleReporter.report_herd_statistics_data.vwp_cow_num']['values'][306]": 35,
        "root['AnimalModuleReporter.report_herd_statistics_data.vwp_cow_num']['values'][309]": 37,
        "root['AnimalModuleReporter.report_herd_statistics_data.vwp_cow_num']['values'][312]": 36
      }
    ]
  },
  "Animal.end_to_end_testing_passing": {
    "values": [
      false
    ]
  }
}
```
